church/children/urls.py
from django.conf.urls import url
from . import views

app_name = 'children'

urlpatterns = [
    url(r'^$', views.children_ministry, name='child'),
]

church/church/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^youths/', include('youths.urls')),
    url(r'^children/', include('children.urls')),
    url(r'^main/', include('main.urls')),
    url(r'^$', views.home, name="home"),
]


urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

church/main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.main_church, name='main'),
]

church/youths/urls.py
from django.conf.urls import url
from . import views

app_name = 'youths'

urlpatterns = [
    url(r'^$', views.youth_ministry, name='youth'),
]

church/children/models.py
from django.db import models

# Create your models here.

class Children(models.Model):
 name = models.CharField(max_length = 100)
 thumb = models.ImageField(blank=True)

 def __str__(self):
  return self.name

church/main/models.py
from django.db import models

# Create your models here.
class Main(models.Model):
 name = models.CharField(max_length = 100)
 thumb = models.ImageField(blank=True)

 def __str__(self):
  return self.name

church/youths/models.py
from django.db import models

# Create your models here.
class Youth(models.Model):
 name = models.CharField(max_length = 100)
 thumb = models.ImageField(blank=True)

 def __str__(self):
  return self.name

church/children/views.py
from django.shortcuts import render
from .models import Children
from django.http import HttpResponse

# Create your views here.

def children_ministry(request):
 children = Children.objects.all()
 return render(request, 'children/children_ministry.html', { 'children': children })

church/church/views.py
from django.shortcuts import render

def home(request):
 return render(request, 'homepage.html')
 

church/main/views.py
from django.shortcuts import render
from .models import Main
from django.http import HttpResponse

# Create your views here.

def main_church(request):
 mains = Main.objects.all()
 return render(request, 'main/main_church.html', { 'mains': mains })

church/youths/views.py
from django.shortcuts import render
from .models import Youth
from django.http import HttpResponse

# Create your views here.

def youth_ministry(request):
 youths = Youth.objects.all()
 return render(request, 'youths/youth_ministry.html', { 'youths': youths })

church/children/templates/children/children_ministry.html
{% extends 'base.html' %}

{% block content%}
 <nav>
  <ul>
   <li><a href="{% url 'youths:youth' %}">Youth ministry</a></li>
   <li><a href="{% url 'home' %}">Home</a></li>
   <li><a href="{% url 'main:main' %}">Main Church</a></li>
  </ul>
 </nav>
 
 <section class="children">
  <h2>Children Ministry</h2>
  <p>Our children ministry is dedicated to bringing up children in the ways of the Lord, so that they grow with Christ
   and stay in Christ. We organise programs for the children. This helps bring the children together and also to display
   their God given talents at an early age in life.</p>
 </section>

 <div id="members">
  <h2 class="title">Choke Parish children</h2>
  {% for child in children %}
  <ul>
   <li>
    <span class="name">{{ child.name }}</span>
   </li>
  </ul>
  {% endfor %}
 </div>

<div id="gallery">
  <h2 class="title">Choke Parish Children Photo Gallery</h2>
  <div class="container">
    {% for child in children %}
    <div>
      <img src="{{ child.thumb.url }}" class="image" />
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

church/main/templates/main/main_church.html
{% extends 'base.html' %}

{% block content%}
<nav>
 <ul>
  <li><a href="{% url 'youths:youth' %}">Youth ministry</a></li>
  <li><a href="{% url 'children:child' %}">Children ministry</a></li>
  <li><a href="{% url 'home' %}">Home</a></li>
 </ul>
</nav>

<div id="members">
 <h2 class="title">Choke Parish Members</h2>
 {% for main in mains %}
 <ul>
  <li>
   <span class="name">{{ main.name }}</span>
  </li>
 </ul>
 {% endfor %}
</div>

<div id="gallery">
 <h2 class="title">Choke Parish Members Photo Gallery</h2>
 <div class="container">
  {% for main in mains %}
  <div>
   <img src="{{ main.thumb.url }}" class="image" />
  </div>
  {% endfor %}
 </div>
</div>
{% endblock %}

church/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Church</title>
 <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
 <div id="wrapper">
  <header>
   <div id="page-banner">
    <h1>Choke Parish</h1>
    <img src="{% static 'image.jpg' %}" alt="church_image">
    <p>We breathe!!</p>
   </div>
  </header>

  {% block content %}
  {% endblock %}

  <form class="salvation">
   <h2>Salvation Form</h2>
   <input type="text" placeholder="Your name..." required>
   <input type="text" placeholder="Your number..." required>
   <input type="email" placeholder="Your email...">
   <textarea cols="30" rows="10" placeholder="Your prayer request..."></textarea>
   <input type="checkbox"> I confess that I have received Jesus Christ as my Lord and personal Saviour
   <a href="mailto: ubongeffiong5@gmail.com">send</a>
  </form>

  <footer>
   <p>Copyright &copy;2021 Choke Parish</p>
  </footer>
 </div>
</body>
</html>

church/templates/homepage.html
{% extends 'base.html' %}

{% block content%}
 <nav>
  <ul>
   <li><a href="{% url 'youths:youth' %}">Youth ministry</a></li>
   <li><a href="{% url 'children:child' %}">Children ministry</a></li>
   <li><a href="{% url 'main:main' %}">Main Church</a></li>
  </ul>
 </nav>
 
 <section class="services">
  <h2>Choke Parish Services</h2>
  <ul>
   <li>
    <p><strong>Sundays:</strong> 9am - 10:30am</p>
   </li>
   <li>
    <p><strong>Tuesdays:</strong> 6pm - 7pm</p>
   </li>
   <li>
    <p><strong>Fridays:</strong> 6pm - 7pm</p>
   </li>
  </ul>
 </section>
 
 <section class="give">
  <h2>Online Giving</h2>
  <p>Make seamless payment of pledges, offerings, tithes and contributions to the church.</p>
  <div class="account">
   <p><strong>Direct Bank Transfers:</strong></p>
   <p class="bank">Zenith Bank <br>2030546021</p>
   <p class="bank">Access Bank <br>0056793451</p>
  </div>
 </section>
 
 <div id="tabbed-content">
  <ul class="tabs">
   <li data-target="#about" class="active">About</li>
   <li data-target="#contact">Contact</li>
  </ul>
  <div class="panel active" id="about">
   <p>About us...</p>
   <p>We bring people together in order to connect them with Christ.</p>
  </div>
  <div class="panel" id="contact">
   <p>Contact us...</p>
   <form action="">
    <input type="text" name="name" id="name" placeholder="Your name..." required />
    <!-- email -->
    <input type="email" name="email" id="email" placeholder="Your email..." required />
    <a href="mailto: ubongeffiong5@gmail.com">send</a>
   </form>
  </div>
 </div>

 <script src="/static/home.js"></script>
{% endblock %}

church/youths/templates/youths/youth_ministry.html
{% extends 'base.html' %}

{% block content%}
  <nav>
    <ul>
      <li><a href="{% url 'home' %}">Home</a></li>
      <li><a href="{% url 'children:child' %}">Children ministry</a></li>
      <li><a href="{% url 'main:main' %}">Main Church</a></li>
    </ul>
  </nav>
 <section class="youth">
  <h2>Youth Ministry</h2>
  <p>Our youth ministry is dedicated to teaching, influencing, guiding and mentoring the youths in the ways of God
   outside the four walls of the church. We organise programs for the youths. This helps bring the youths together and
   also to display their God given talents.</p>
 </section>

 <div id="members">
  <h2 class="title">Choke Parish Youths</h2>
  {% for youth in youths %}
  <ul>
   <li>
    <span class="name">{{ youth.name }}</span>
   </li>
  </ul>
  {% endfor %}
 </div>

 <div id="gallery">
  <h2 class="title">Choke Parish Youths Photo Gallery</h2>
  <div class="container">
    {% for youth in youths %}
    <div>
      <img src="{{ youth.thumb.url }}" class="image"/>
    </div>
    {% endfor %}
  </div>
 </div>
{% endblock %}